<html>
<head>
<title>RegistrationForm</title>
</head>
<body>
<linkhref="registration.css"type="text/css"rel="stylesheet"/>
<linkhref="../style.css"type="text/css"rel="stylesheet"/>
<ul>
<listyle="float:right;"><ahref="../index.php">Backto
homepage</a></li>
</ul>
<h2>Customer</h2>
<formname="form1"action='modified.php'method='POST'
enctype="multipart/form-data">
<divclass="container">
<divclass="form_group">
<label>FirstName:</label>
<inputtype="text"name="First_Name"value=""required/>
</div>
<divclass="form_group">
<label>MiddleName:</label>
<inputtype="text"name="Middle_Name"value=""required
/>
</div>
<divclass="form_group">
<label>LastName:</label>
<inputtype="text"name="Last_Name"value=""required/>
</div>
<divclass="form_group">
<label>Gender: </label><inputtype="radio"name=
"Gender"value="M"required/>Male<inputtype="radio"name=
"Gender"value="F"required/>Female
</div>
<divclass="form_group">
<label>DateofBirth: </label><inputtype="date"name=
"DOB"value=""required/>
</div>
<divclass="form_group">
<label>Address:</label>
<inputtype="text"name="Address"value=""required/>
</div>
<divclass="form_group">
<label>Pincode:</label>
<inputtype="text"name="Pincode"value=""required/>
</div>
<divclass="form_group">
<label>ContactNumber:</label>
<inputtype="text"name="Contact_Number"value=""
requiredpattern="[0-9]{10}"/>
</div>
<divclass="form_group">
<label>MotherName:</label>
<inputtype="text"name="Mother_Name"value=""
required/>
</div>
<divclass="form_group">
<label>MotherStatus:</label>
<inputtype="radio"name="Mother_Status"value="A"
required/>Alive <inputtype="radio"name="Mother_Status"value=
"D"required/>Dead
</div>
<divclass="form_group">
<label>FatherName:</label>
<inputtype="textbox"name="Father_Name"value=""
required/>
</div>
<divclass="form_group">
<label>FatherStatus:</label>
<inputtype="radio"name="Father_Status"value="A"
required/>Alive <inputtype="radio"name="Father_Status"value=
"D"required/>Dead
</div>
<divclass="form_group">
<label>MaritalStatus:</label>
<inputtype="radio"name="Marital_Status"value="S"
required/>Single <inputtype="radio"name="Marital_Status"value=
"M"required/>Married
</div>
<divclass="form_group">
<label>SpouseName:</label>
<inputtype="textbox"name="Spouse"value=""/>
</div>
<divclass="form_group">
<inputtype="submit"value="submit"/>
</div>
<divclass="form_group">
<inputtype="reset"value="reset"/>
</div>
</div>
</form>
</body>
</html>
