<html>
<head>
<title>
LifeInsurance
</title>
</head>
<body>
<linkhref="policy/registration.css"type="text/css"rel="stylesheet"/>
<linkhref="style.css"type="text/css"rel="stylesheet"/>
<nav>
<ul>
<li><ahref="agent/agent.php"><h3>Agent
Registration</h3></a></li>
<li><ahref="client/client.php"><h3>Client
Registration</h3></a></li>
<li><ahref="policy/policy.php"><h3>Policy
Registration</h3></a></li>
<li><ahref="premium/premium.php"><h3>Premium
Registration</h3></a></li>
<li><ahref="agent/modified1.php"><h3>Agents
Data</h3></a></li>
</ul>
</nav>
<divclass="title">
<h1><center>InsuranceDatabaseSystem</center></h1>
</div>
<divclass="links">
<divclass="subtitle">
<h2><center>LinkstoDatasandregistrationpages</center></h2>
</div>
<ulstyle="position:fixed;bottom:0;width:100%;">
<li><ahref="client/modified1.php"><h3>Customers
Data</h3></a></li>
<li><ahref="policy/modified1.php"><h3>Policies Data</h3></a></li>
<li><ahref="premium/modified1.php"><h3>Premiums
Data</h3></a></li>
</ul>
</div>
</html>
