<?php
include"../connection.php";
$sql="select*fromcustomer";
$result=mysqli_query($conn,$sql);
?>
<html>
<body>
<linkhref="registration.css"type="text/css"rel="stylesheet"/>
<linkhref="../style.css"type="text/css"rel="stylesheet"/>
<ul>
<listyle="float:right;"><ahref="../index.php">Backto
homepage</a></li>
</ul>
<h1><center>CustomerData</center></h1>
<tablewidth="100%"border="1"cellspacing="1"
cellpadding="1">
<tr>
<td>CustomerNumber</td>
<td>FirstName</td>
<td>MiddleName</td>
<td>LastName</td>
<td>Gender</td>
<td>DOB</td>
<td>Address</td>

<td>Pincode</td>
<td>ContactNumber</td>
<td>MotherName</td>
<td>MotherStatus</td>
<td>FatherName</td>
<td>FatherStatus</td>
<td>MaritalStatus</td>
<td>Spouse</td>
<tdcolspan="2">Action</td>
</tr>
<?php
while($row=mysqli_fetch_object($result)){
?>
<tr>
<td>
<?phpecho$row->Customer_Num;?>
</td>
<td>
<?phpecho$row->First_Name;?>
</td>
<td>
<?phpecho$row->Middle_Name;?>
</td>
<td>
<?phpecho$row->Last_Name;?>
</td>
<td>
<?phpecho$row->Gender;?>
</td>
<td>
<?phpecho$row->DOB;?>
</td>
<td>
<?phpecho$row->Address;?>
</td>
<td>
<?phpecho$row->Pincode;?>
</td>
<td>
<?phpecho$row->Contact_Number;?>
</td>
<td>
<?phpecho$row->Mother_Name;?>
</td>
<td>
<?phpecho$row->Mother_Status;?>
</td>
<td>
<?phpecho$row->Father_Name;?>
</td>
<td>
<?phpecho$row->Father_Status;?>
</td>
<td>
<?phpecho$row->Marital_status;?>
</td>
<td>
<?phpecho$row->Spouse;?>
</td>
<td><ahref="delete.php?id=<?phpecho$row
->Customer_Num;?>"onclick="returnconfirm('AreYouSure')">Delete
</a></td>
</tr>
<?php}?>
</table>
</body>
</html>
