<html>
<head>
<title>RegistrationForm</title>
</head>
<body>
<linkhref="registration.css"type="text/css"rel="stylesheet"/>
<linkhref="../style.css"type="text/css"rel="stylesheet"/>
<ul>
<listyle="float:right;"><ahref="../index.php">Backto
homepage</a></li>
</ul>
<h2>Policy</h2>
<formname="form1"action='modified.php'method='POST'
enctype="multipart/form-data">
<divclass="container">
<divclass="form_group">
<label>PolicyNumber:</label>
<inputtype="text"name="Policy_Num"requiredpattern="[0
-9]{9}"/>
<fontsize="1">Enter9digit number.</font>
</div>
<divclass="form_group">
<label>CustomerNumber:</label>
<selectname="Customer_Num">
<?php
include"../connection.php";
$sql="select*fromcustomer";
$result=mysqli_query($conn,$sql);
$i=0;
while($row=mysqli_fetch_object($result)){
$i++;
?>
<optionvalue="<?phpecho$row
->Customer_Num?>"><?phpecho$row->Customer_Num?></option>
<?php}?>
</select>
</div>
<divclass="form_group">
<label>AgentCode:</label>
<selectname="Agent_code">
<?php
include"../connection.php";
$sql="select*fromagent";
$result=mysqli_query($conn,$sql);
$i=0;
while($row=mysqli_fetch_object($result)){
$i++;
?>
<optionvalue="<?phpecho$row
->Agent_code?>"><?phpecho$row->Agent_code?></option>
<?php}?>
</select>
</div>
<divclass="form_group">
<label>DOC:</label>
<inputtype="date"name="DOC"value=""required/>
</div>
<divclass="form_group">
<label>Product:</label>
<inputtype="text"name="Product"value=""required/>
</div>
<divclass="form_group">
<label>SumAssured:</label>
<inputtype="text"name="Sum_assured"value=""required
/>
</div>
<divclass="form_group">
<label>PaymentPeriod:</label>
<inputtype="text"name="Payment_period"value=""
required/>
</div>
<divclass="form_group">
<label>InsurancePeriod:</label>
<inputtype="text"name="Ins_period"value=""required/>
</div>
<divclass="form_group">
<label>Premiummode:</label>
<inputtype="radio"name="mode"value="MLY"required
/>Monthly
<inputtype="radio"name="mode"value=
"YLY"required/>Yearly
<inputtype="radio"name="mode"value=
"QLY"required/>Quarterly
<inputtype="radio"name="mode"value=
"SSS"required/>Singlepremium
</div>
<divclass="form_group">
<inputtype="submit"value="submit"/>
</div>
<divclass="form_group">
<inputtype="reset"value="reset"/>
</div>
</div>
</form>
</body>
</html>
