<?php
include"input1.php";
$f=0;
?>
<html>
<head>
<title>PolicyInformation</title>
</head>
<body>
<linkhref="registration.css"type="text/css"rel="stylesheet"/>
<h2>Premium</h2>
<formname="form1"action='modified.php'method='POST'
enctype="multipart/form-data">
<divclass="container">
<?phpwhile($row=mysqli_fetch_object($result)){?>
<divclass="form_group">
<label>PolicyNumber:</label><label><?php$f=1;echo$row
->Policy_Num;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>CustomerNumber:
</label><label><?phpecho$row->Customer_Num;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>AgentCode:</label><label><?php
echo$row->Agent_code;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>DOC:</label><label><?phpecho
$row->DOC;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>Product:</label><label><?phpecho
$row->Product;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>SumAssured:</label><label><?php
echo$row->Sum_Assured;?></label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>PaymentPeriod:
</label><label><?phpecho$row->Pay_Period;?>years</label>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>InsurancePeriod:
</label><label><?phpecho$row->Ins_Period;?>years</label>
</div>
<divclass="form_group">
<inputname='Pol'value="<?phpecho$row
->Policy_Num;?>"hidden>
</div>
<divclass="form_group">
</div>
<divclass="form_group">
<label>Premiumpayed?:</label>
<inputtype="radio"name="pay"value="Yes"required
/>Yes
<inputtype="radio"name="pay"value=
"No"required/>No
</div>
<divclass="form_group">
<inputtype="submit"value="submit"/>
</div>
<divclass="form_group">
<inputtype="reset"value="reset"/>
</div>
<?php}
if($f==0){
echo"PolicyNotFound";
echo"<ahref='premium.php'>Backtosearch
page</a>";
}?>
</div>
</form>
</body>
</html>
